vich_uploader:
    db_driver: orm

    mappings:
       mbacke:
           uri_prefix: /images/mbacke
           upload_destination: '%kernel.project_dir%/public/images/mbacke'
           namer: Vich\UploaderBundle\Naming\UniqidNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
